# Generated by Django 3.2 on 2023-07-30 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram_backend', '0002_auto_20230727_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='recipes/', verbose_name='Картинка'),
        ),
    ]
